apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-app
  namespace: default
  labels:
    app:  nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nginx-app
    spec:
      containers:
      - name:  nginx-app
        image:  nginx-app
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  web

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app:  nginx-app
  type:  ClusterIP
  ports:
  - name:  web
    port:  80
    targetPort:  80